name: DockerCommenter
on:
  pull_request:
    branches:
    - main
env:
  GOPRIVATE: "github.com/Khan"
  GOFLAGS: "-trimpath"
  GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
  COMMENTARY_ACTION_TYPE: "docker action"
jobs:
  docker_commenter:
#    runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Commentary
      uses: docker://docker.io/stevenacoffman/commentary:v0.4.0
